/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import tiptapEditor from "@notum-cz/strapi-plugin-tiptap-editor/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.tsx";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    "tiptap-editor": tiptapEditor,
    "strapi-cloud": strapiCloud,
    "users-permissions": usersPermissions,
  },
});
